export {};
describe("JaJaJa", () => {
  it("passes", () => {
    cy.visit("http://localhost:3000");
    cy.get("input[name='title']").should("exist");
    cy.get("input[name='title']").type("JaJaJa");
    const peopleSection = cy.get("#People");
    peopleSection.should("exist");
    const increase = peopleSection.get("button[name='increase']");
    increase.click().click().click().click();
    cy.get("input[name='name']").should("have.length", 4);
    cy.get('[data-cy="person-0"]').type("Nathan Sorkin");
    cy.get('[data-cy="person-1"]').type("Emily Prusak");
    cy.get('[data-cy="person-2"]').type("Sarah Longnecker");
    cy.get('[data-cy="person-3"]').type("Jordan Longnecker");
    const addItemButton = cy.contains("Add Item");
    addItemButton.click();
    cy.get('[data-cy="addInputTitle"]').type("Quesadilla");
    cy.get('[data-cy="addInputValue"').type("14.00");
    cy.get('[data-cy="include-0"]').click();
    cy.get('[data-cy="item-submit"]').click();
    addItemButton.click();
    cy.get('[data-cy="addInputTitle"]').type("Chorizo Burrito");
    cy.get('[data-cy="addInputValue"').type("15.00");
    cy.get('[data-cy="include-1"]').click();
    cy.get('[data-cy="item-submit"]').click();
    addItemButton.click();
    cy.get('[data-cy="addInputTitle"]').type("Pollo Burrito");
    cy.get('[data-cy="addInputValue"').type("18.00");
    cy.get('[data-cy="include-2"]').click();
    cy.get('[data-cy="item-submit"]').click();
    addItemButton.click();
    cy.get('[data-cy="addInputTitle"]').type("Tacos");
    cy.get('[data-cy="addInputValue"').type("10.00");
    cy.get('[data-cy="include-3"]').click();
    cy.get('[data-cy="item-submit"]').click();
    addItemButton.click();
    cy.get('[data-cy="addInputTitle"]').type("Nachos");
    cy.get('[data-cy="addInputValue"').type("18.00");
    cy.get('[data-cy="sharedSelect"').click();
    cy.get('[data-cy="selectAll"]').click();
    cy.get('[data-cy="item-submit"]').click();
    cy.get('[data-cy="taxInput"]').type("6.66");
    cy.get('[data-cy="tipInput"]').type("16.34");
  });
});
