import { receiptAtom } from "$/store/store";
import { useAtom } from "jotai";
import Head from "next/head";
import Header from "$/components/header";
import { Items } from "$/components/Items";
import { People } from "$/components/People";
import { ReceiptMeta } from "../components/ReceiptMeta";
import { TaxAndTip } from "../components/TaxAndTip";
import { Share } from "../components/Share";

export default function Home() {
  const [receipt, setReceipt] = useAtom(receiptAtom);

  const handleUpdateReceiptMeta = (name: string, value: string | number) => {
    setReceipt({ ...receipt, [name]: value });
  };

  return (
    <>
      <Head>
        <title>Spill</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="wrapper">
        <Header />
        <div className="flex flex-col gap-4 max-w-md mx-auto">
          <ReceiptMeta
            receipt={receipt}
            handleUpdateReceiptMeta={handleUpdateReceiptMeta}
          />
          <People />
          <Items />
          <TaxAndTip
            tax={receipt.tax}
            tip={receipt.tip}
            handleUpdateReceiptMeta={handleUpdateReceiptMeta}
          />
        </div>
      </section>
      <Share receipt={receipt} />
    </>
  );
}
